### ISSUE TITLE
secure and insecure download and install

### ISSUE THREAD

**Issue by KernFerm** [Lightn1ng0/Lightn1ng0_AI_Aimbot#1]
make secure download install  and insecure download install for 

secure download install  - for those who can download and use the secure and want security without middleman attacks

insecure for those whom cant use the secure 

have two different versions 

make more ethical ,, 

having insecure makes your product vul  makes it easy target

**Comment by Lightn1ng0** [comment]
Should be more secure installing with winforms app instead of .bat file.
